#!/bin/sh

echo "Emonhub installation script for emonPi"

### set git cloned location
GIT_PATH=/home/pi/emonhub

if [ ! -d /home/pi ] ; then
  {
    echo "Directory /home/pi does not exist, this installation script is for raspberrypi installation"
    exit
  }
fi


### set location to install emonhub.py etc
INST_PATH=/usr/share/emonhub

### create linked directory for emonhub.py etc
sudo rm -r -f $INST_PATH
sudo ln -s $GIT_PATH/src $INST_PATH

### install init script stub
sudo install ${GIT_PATH}/service/emonhub.stub /etc/init.d/emonhub
### modify stub script to call script in github dir
sudo /bin/sh -c "echo '. ${GIT_PATH}/service/emonhub \$@' >> /etc/init.d/emonhub"

CONFDEF="${GIT_PATH}/conf/default/emonhub"

### link default locations file (and backup) but only if changed
if [ ! -L "/etc/default/emonhub" ] || [ $( readlink /etc/default/emonhub ) != "${CONFDEF}" ] ; then
    sudo ln -s --backup=numbered ${CONFDEF} /etc/default/emonhub
fi

### create folder and move settings file (unless it exists already)
if [ ! -f /home/pi/data/emonhub.conf ] ; then
    sudo install -v $GIT_PATH/conf/emonpi.default.emonhub.conf /home/pi/data/emonhub.conf
fi

# launch at start-up (SysV init)
sudo update-rc.d emonhub defaults 99


### create "emonhub" user
sudo useradd -M -r -G dialout,tty -c "emonHub user" emonhub

### Install systemd unit file regardless, in case the host is switched to
### systemd in the future
sudo install --compare $GIT_PATH/service/emonhub.service /etc/systemd/system/

# FIXME is this check is Debian specific?  Does this matter?
INITDEST=$( readlink /sbin/init )
if test "${INITDEST#*systemd}" != "systemd" ; then
    sudo systemctl daemon-reload
    sleep 1 # daemon-reload is not instant apparently

    # launch at start-up (systemd)
    sudo systemctl enable emonhub.service && echo 'systemd unit enabled.' \
        && echo 'Start manually with:' \
        && echo \
        && echo 'systemctl start emonhub.service' \
        && echo \
        && echo '...or if updating, restart with:' \
        && echo \
        && echo 'systemctl restart emonhub.service' \
        && echo \
        && echo 'Log output can be followed with:' \
        && echo \
        && echo 'jounalctl -u emonhub -f' \
        && echo
    if [ -f /var/run/emonhub.pid ] ; then
        echo '*** IMPORTANT ***'
	echo 'use:'
	echo
	echo "sudo /bin/sh -c '( start-stop-daemon --stop --retry=INT/30/KILL/5 --pidfile /var/run/emonhub.pid && rm /var/run/emonhub.pid )'"
	echo
	echo 'to stop the previously running emonhub instance prior to systemd unit file installation'
    fi
fi
